### ISSUE TITLE
Landmark Connections

### ISSUE THREAD

**Issue by lghasemzadeh** [patlevin/face-detection-tflite#1]
Hello @patlevin,

I tried the codes, I have two problems:
1. for face landmark --> when I want to render the landmarks into data, it can not find the landmark connections, what should I do?
2. for the iris detection --> the script can not find the right eye (can not recolor that eye), do have any idea?

Thank you,
Leila

**Comment by shurru** [comment]
I'm having the same trouble with the right eye recoloring. Would appreciate some help on that.

**Comment by patlevin** [comment]
@lghasemzadeh @shurru Thanks for reporting the error! Turns out there was a rounding error that is fixed now.
The latest release version contains a fix for that.

As for the face landmark connections, I forgot to include them 🤦‍♂️. I will add them in the next version, but if you can't wait you can find them [here](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/face_mesh/calculators/face_landmarks_to_render_data_calculator.cc#L33). The comments give a rough idea about the landmarks (lips, face oval, etc.).

I'm not sure if there's more data like that so I have to take a deeper look and test it. This might take a little bit of time and I wanted to get the bugfix out first.
