### ISSUE TITLE
Group detection error

### ISSUE THREAD

**Issue by edhuardotierrez** [patlevin/face-detection-tflite#3]
Hi.

First of all, thanks for this project (amazing). 
But recently i'm getting "no faces" when using the image below.

![nasa01](https://user-images.githubusercontent.com/5994362/123321428-59073a80-d509-11eb-86f3-d099304a248d.jpg)

--

Code used:

```python
from fdlite import FaceDetection
from fdlite.render import Colors, detections_to_render_data, render_to_image 
from PIL import Image

image = Image.open('123321428-59073a80-d509-11eb-86f3-d099304a248d.jpg')
detect_faces = FaceDetection()
faces = detect_faces(image)
if len(faces) == 0:
    print('no faces detected :(')
else:
    render_data = detections_to_render_data(faces, bounds_color=Colors.GREEN)
    render_to_image(render_data, image).show()
```

**Comment by patlevin** [comment]
Thank you for reporting the issue👍

Turns out, this is more a problem with the documentation (or bad defaults?). By default, the model used is optimised for front cameras, i.e. selfie-mode, and expects inputs with close-up faces.

The problem with group images like this can easily be fixed by using the model for the back-facing camera instead:

```python
from fdlite import FaceDetection, FaceDetectionModel
from fdlite.render import Colors, detections_to_render_data, render_to_image 
from PIL import Image

image = Image.open('123321428-59073a80-d509-11eb-86f3-d099304a248d.jpg')
detect_faces = FaceDetection(model_type=FaceDetectionModel.BACK_CAMERA)
faces = detect_faces(image)
if len(faces) == 0:
    print('no faces detected :(')
else:
    render_data = detections_to_render_data(faces, bounds_color=Colors.GREEN)
    render_to_image(render_data, image).show()
```

which would result in proper detections. I will update the documentation accordingly.

Cheers

**Comment by edhuardotierrez** [comment]
You're correct, I probably didn't check this point in the documentation. 
Thanks.
